# Generated by Django 3.2.9 on 2021-11-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('availability_status', models.BooleanField(default=True)),
                ('metadata', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
